openapi: 3.0.3

info:
  title: electerm-sync-server-go
  description: A golang server to sync electerm data.
  contact:
    name: dragonish
    url: https://github.com/dragonish/electerm-sync-server-go
    email: no.web.developer@outlook.com
  license:
    name: MIT License
  version: 1.0.0

servers:
  - url: http://{host}:{port}
    variables:
      host:
        default: localhost
        description: The host of the server
      port:
        default: '7837'
        description: The port of the server

paths:
  /test:
    get:
      summary: Test the server
      security: []
      responses:
        '200':
          $ref: '#/components/responses/ok'
  /api/sync:
    get:
      summary: Get electerm sync data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Resource not found
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: Test electerm sync
      responses:
        '200':
          $ref: '#/components/responses/ok'
    put:
      summary: Sync electerm data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          description: Bad request with parse error
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

components:
  responses:
    ok:
      description: Successful response
      content:
        text/plain:
          schema:
            type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
