name: Release

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_REPO: giterhub/electerm-sync-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/riscv64
            linux/s390x
